// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyPatch(arg1, arg2) {
  return window['go']['main']['App']['ApplyPatch'](arg1, arg2);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GitGetStatus(arg1) {
  return window['go']['main']['App']['GitGetStatus'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitPush(arg1, arg2, arg3) {
  return window['go']['main']['App']['GitPush'](arg1, arg2, arg3);
}

export function ParsePatchExtract(arg1) {
  return window['go']['main']['App']['ParsePatchExtract'](arg1);
}

export function Rollback(arg1) {
  return window['go']['main']['App']['Rollback'](arg1);
}

export function SelectProjectDir() {
  return window['go']['main']['App']['SelectProjectDir']();
}
