// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function ApplyPatch(arg1:string,arg2:string):Promise<string>;

export function GetHistory():Promise<Array<models.HistoryItem>>;

export function GitGetStatus(arg1:string):Promise<Record<string, any>>;

export function GitPull(arg1:string):Promise<string>;

export function GitPush(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ParsePatchExtract(arg1:string):Promise<Array<services.PatchEntry>>;

export function Rollback(arg1:string):Promise<void>;

export function SelectProjectDir():Promise<string>;
